CREATE DATABASE noticias_reif;
USE DATABASE noticias_reif;

--Tablas

CREATE TABLE news(
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(60) NOT NULL,
    content VARCHAR(10000) NOT NULL,
    image VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    subtitle VARCHAR(50) NOT NULL,
    section VARCHAR(50) NOT NULL,
    author VARCHAR(60) NOT NULL
)

CREATE TABLE commentary{
id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL,
commentary VARCHAR(400) NOT NULL,
id_news INT NOT NULL,
FOREIGN KEY (id_news) REFERENCES news(id)
}

-- Algunos datos por si te sirven


INSERT INTO noticias_reif.commentary (id, name, email, commentary, id_news) VALUES (2, 'Raul Reif', 'raulreif@outlook.com', 'Esto es un comentario de prueba', 1);
INSERT INTO noticias_reif.commentary (id, name, email, commentary, id_news) VALUES (27, 'Juan Vela', 'juanvela@gmail.com', 'Yo estuve allí, fue un combate impresionante y muy desputado donde cada uno recibio hasta en el carnet de indentidad.', 13);
INSERT INTO noticias_reif.commentary (id, name, email, commentary, id_news) VALUES (28, 'Prueba Pruebas', 'prueba@prueba.com', 'Este es un comentario de prueba !!', 1);
INSERT INTO noticias_reif.news (id, title, content, image, created_at, subtitle, section, author) VALUES (1, 'Los representantes de Compromís en Corts ', 'Así lo han avanzado este sábado durante una encuentro en Chiva para planificar y estructurar el trabajo y la acción política para el próximo año. En este sentido, el síndic de Compromís en Les Corts, Fran Ferri, ha declarado que "mientras las derechas intentan dividir y hacer el mal", la coalición "vertebra el territorio con la figura del diputado comarcal".
Ferri ha explicado que "con esta figura, cada una de las 34 comarcas contará con un representante directo en el parlamento valenciano que se encargará de trasladar las diferentes inquietudes y necesidades", ha precisado la formación en un comunicado.', 'https://upload.wikimedia.org/wikipedia/commons/6/68/Comprom%C3%ADs_%28isotip%29.svg', '2020-01-25 22:27:00', 'Grupo de Compromis', 'Policy', 'Raul Reif Tamarit');
INSERT INTO noticias_reif.news (id, title, content, image, created_at, subtitle, section, author) VALUES (4, 'Angular', 'El contenido de prueba de nuestro curso.', 'https://upload.wikimedia.org/wikipedia/commons/c/cf/Angular_full_color_logo.svg', '2020-01-26 22:23:01', 'Curso gratuito de angular', 'Games', 'Raul Reif Tamarit');
INSERT INTO noticias_reif.news (id, title, content, image, created_at, subtitle, section, author) VALUES (6, 'Madison, WI', 'Founded in 1829 on an isthmus between Lake Monona and Lake Mendota, Madison was named the capital of the Wisconsin Territory in 1836.', 'https://ionicframework.com/docs/demos/api/card/madison.jpg', '2020-01-31 15:02:19', 'Destination', 'Policy', 'Ionic');
INSERT INTO noticias_reif.news (id, title, content, image, created_at, subtitle, section, author) VALUES (7, '  Valencia CF  Garay tiene roto el ligamento cruzado y dice ', 'Ezequiel Garay tiene afectados los ligamentos de la rodilla derecha. El Valencia ha confirmado mediante un confuso parte médico que el jugador argentino tiene una lesión en los ligamentos de la rodilla derecha y que por tanto va a estar de baja durante un largo peridodo de tiempo.El club no especifica el tiempo que utilizará el central para recuperarse ni la gravedad de la lesión, pero MARCA ha podido confirmar que se trata de una lesión grave de rotura del ligamento cruzado y que el argentino dice adiós a la temporada.
Garay que se retiró por su porpio pie, ha sido sometido a diversas pruebas radiológicas durante el día de hoy que han confirmado la gravedad de la lesión y por tanto no podrá volver a jugar esta campaña. El club podría incluso ejercer la posibilidad de fichar un recambio debido a la gravedad del problema.Hay que recordar que Garay no ha renovado aún su contrato con el Valencia y a final de campaña termina su relación laboral con el club por lo que ahora se plantea una situación mucha más delicada.', 'https://e00-marca.uecdn.es/assets/multimedia/imagenes/2020/02/02/15806598678014.jpg', '2020-02-02 17:56:03', 'Ezequiel Garay tiene afectados los ligamentos de l', 'Sports', 'MARCA');
INSERT INTO noticias_reif.news (id, title, content, image, created_at, subtitle, section, author) VALUES (8, 'Alex Isak no perdona', 'Alex Isak ha dejado claro que el perdón de Imanol Alguacil no va a ser suficiente para que Willian José vuelva a ser el delantero titular de la Real Sociedad, al conseguir el sueco su quinto gol en los cuatro encuentros en los que ha jugado de inicio por el brasileño. Lo triste para el ''19'' txuriurdin ha sido que su undécimo tanto en la presenta temporada fue el primero que no ha servido para sumar, tras colaborar los anteriores en siete triunfos y un empate.Isak ha sido uno de los cinco jugadores a los que Imanol ha mantenido en el once, con respecto a la eliminatoria de Copa con Osasuna y pensando parece en la de este próximo jueves en el Bernabéu contra el Real Madrid, al realizar el técnico de Orio seis variaciones, con suplencias para Mikel Oyarzabal y Martin Odegaard, entre otros.', 'https://e00-marca.uecdn.es/assets/multimedia/imagenes/2020/02/02/15806539956047.jpg', '2020-02-02 17:57:15', 'El sueco marcó su quinto gol en cuatro partidos', 'Sports', 'MARCA');
INSERT INTO noticias_reif.news (id, title, content, image, created_at, subtitle, section, author) VALUES (10, '  Liga Endesa  Suspendido el Fuenlabrada-Granca en el tercer', 'El partido entre el Montakit Fuenlabrada y el Herbalife Gran Canaria ha sido aplazado debido al abombamiento, por motivos desconocidos, de una de las láminas que conforman el parqué del Pabellón Fernando Martín y la imposibilidad de solucionarlo en el momento y continuar la disputa del encuentro en las condiciones necesarias. Restaban 5:04 para la finalización del tercer cuarto cuando los colegiados pararon el partido para informar a los dos entrenadores, Paco García y Fotis Katsikaris, de esta circunstancia, y tras consultarlo con el comisario del encuentro, Ricardo Salguero, decidieron suspender el partido.Fue uno de los tres árbitros, Emilio Pérez Pizarro, el que se dio cuenta de esta anómala situación al estar a punto de tropezar en la zona cerca del aro en la que atacaba el Montakit Fuenlabrada en la segunda mitad y paró el encuentro ante el irregular estado del parqué y el peligro que suponía para la integridad de jugadores y colegiados. Una situación peculiar que gana extrañeza al ser el parqué nuevo, ya que, según informan desde el club madrileño, se cambió el pasado verano para la actual campaña.', 'https://e00-marca.uecdn.es/assets/multimedia/imagenes/2020/02/01/15805906033675.jpg', '2020-02-02 18:05:02', 'Parte del parquet se levantó y no pudo seguir jugá', 'Sports', 'ABC');
INSERT INTO noticias_reif.news (id, title, content, image, created_at, subtitle, section, author) VALUES (11, '  Liga Endesa  El Estudiantes homenajea a Kobe Bryant en su ', 'El Movistar Estudiantes hizo este jueves su tradicional foto de cantera en el Polideportivo Magariños y tuvo un recuerdo especial para Kobe Bryant y su hija Gianna, recientemente fallecidos en un accidente de helicóptero.La cantera inclusiva del conjunto estudiantil, con sus 2.000 jugadores y jugadoras, incluyendo los profesionales de los conjuntos de Liga Endesa y Liga Femenina 2 y los entrenadores de todos los equipos formaron en la pista del Magariños un número 24, el mismo que llevó el escolta de los Lakers en sus últimas temporadas.', 'https://e00-marca.uecdn.es/assets/multimedia/imagenes/2020/01/30/15804100095272.jpg', '2020-02-02 18:07:22', 'Los jugadores del club colegial formaron el número', 'Sports', 'ABC');
INSERT INTO noticias_reif.news (id, title, content, image, created_at, subtitle, section, author) VALUES (12, 'La cuesta de enero llevó a Laura Ester hasta la gloria', 'La cuesta de enero resultó una escalera hacia la gloria para la guardameta de la selección femenina de waterpolo, Laura Ester. En la primera semana se conoció que había sido elegida por segunda vez mejor waterpolista europea de 2019 -la anterior fue en 2017-, y con ese galardón disputó el Campeonato de Europa, donde España se proclamó campeona el pasado sábado. Entre medias, Laura cumplía 30 años, los doce últimos como componente del equipo nacional. Otro Europeo fue su primer gran campeonato, el disputado en Málaga, y ahí el waterpolo femenino español inauguró su palmarés internacional.Aquella guardameta menuda se ha convertido en una de las grandes y más laureadas de su deporte. "Son muchos años", recapitula tras las recepciones que los Reyes y el Presidente del Gobierno dieron a las selecciones femenina y masculina. "El mayor cambio es la experiencia, que es muy importante en la posición de portera; el tener cabeza y tranquilidad; ser consciente de que los partidos son muy largos, que no es como se empieza, sino como se acaba".', 'https://e00-marca.uecdn.es/assets/multimedia/imagenes/2020/01/31/15804961329784.jpg', '2020-02-02 18:08:10', 'Mejor waterpolista europea y campeona con la selec', 'Sports', 'MARCA');
INSERT INTO noticias_reif.news (id, title, content, image, created_at, subtitle, section, author) VALUES (13, '  MMA - Artes Marciales Mixtas  La condición de Khabib a May', 'No hace ni una semana que Conor McGregor aniquiló a Donald Cerrone en UFC 246 y al irlandés no paran de salirle novias. Desde luego se ha hablado de la revancha contra Khabib Nurmagomedov, el combate que más ansían los espectadores, aunque tanto el irlandés como el ruso están siendo tentados no sólo desde su deporte sino también desde el boxeo.Los guiños han sido muy directos hacia The Notorious por parte de Pacquiao y de Mayweather. Este último, de hecho, también apuntó a Nurmagomedov en sus redes sociales, y es que sabe que el crossover de invictos tendría mucho tirón. Lo primero para Khabib será defender por tercera vez su título del peso ligero el 19 de abril en UFC 249, contra Tony Ferguson.', 'https://e00-marca.uecdn.es/assets/multimedia/imagenes/2020/01/23/15798083953784.png', '2020-02-02 18:08:49', 'El boxeo lo trabajaría "con Lomachenko"', 'Sports', 'MMA');
INSERT INTO noticias_reif.news (id, title, content, image, created_at, subtitle, section, author) VALUES (14, 'Djokovic se sitúa con 17 grandes y pone cerco a Nadal y a Fe', 'Novak Djokovic parecía descartado en la lucha por ser el mejor tenista de la historia, algo que marca el número de títulos de ''Grand Slam'' cuando cedió en los octavos del pasado US Open con Stan Wawrinka aquejado de unas molestias en su codo. Ni tan siquiera él sabía si la lesión le obligaría a pasar de nuevo por el quirófano.Rafael Nadal ganaría en las pistas de Flushing Meadows y elevaría su contados de ''majors'' a 19. Se quedaba a uno de Roger Federer del que nunca había estado tan cerca. El español perdió la opción de igualar al suizo en Melbourne cuando cedió en la antepenúltima ronda ante Dominic Thiem.', 'https://e00-marca.uecdn.es/assets/multimedia/imagenes/2020/02/02/15806328036250.jpg', '2020-02-02 17:11:46', 'El serbio, un año menos que el español y seis meno', 'Sports', 'MARCA');
INSERT INTO noticias_reif.news (id, title, content, image, created_at, subtitle, section, author) VALUES (15, 'Barones del PSOE se suman al PP para exigir 2.500 millones a', 'La asfixia financiera que denuncian las autonomías reaviva el frente judicial contra el Gobierno. Mientras el sistema de financiación autonómica lleva seis años caducado, se recrudece el enfado de las regiones por los 2.500 millones que les debe el Estado por la liquidación del IVA de 2017. Tras la batalla de las entregas a cuenta de la financiación, en este nuevo frente varios barones socialistas amenazan con unirse a Cataluña y las comunidades del PP. Castilla-La Mancha anuncia que acudirá a los tribunales, y Asturias y Aragón se plantean seguir ese camino.
El malestar de las comunidades autónomas va ya más allá de la gesticulación que se les presupone a los territorios populares para apoyar la labor de oposición de Pablo Casado. La preocupación afecta a todas las regiones —a excepción de Navarra y el País Vasco, que recaudan sus propios impuestos, y Canarias, que no tiene IVA—, aunque de momento solo Cataluña y Madrid han llevado al Gobierno a los tribunales por la liquidación de ese impuesto; Andalucía y Galicia han anunciado esta semana que también optarán por judicializar su caso.', 'https://concepto.de/wp-content/uploads/2015/04/politica.jpg-e1549511688972.jpg', '2020-02-02 15:37:15', 'Castilla-La Mancha emprenderá acciones judiciales ', 'Policy', 'El País');
INSERT INTO noticias_reif.news (id, title, content, image, created_at, subtitle, section, author) VALUES (16, 'El Constitucional considera “manifiesta” y “reiterada” la de', 'El Tribunal Constitucional considera que la desobediencia del Palament está siendo “manifiesta” y “reiterada”. Lo expone en sus dos últimas sentencias sobre las declaraciones de la Cámara catalana en reivindicación del derecho a la autodeterminación y de crítica al Rey. Son las resoluciones en las que los magistrados instaron a la Fiscalía a plantearse la presentación de una querella contra el presidente del Parlament, Roger Torrent. El Constitucional dice que no le corresponde iniciar acciones penales, pero pone la munición en manos de los fiscales.
Las dos últimos autos del Tribunal Constitucional sobre declaraciones del Parlament son un auténtico pliego de cargos contra los representantes de los partidos independentistas en la Mesa de la Cámara, empezando por su presidente, Roger Torrent. Las resoluciones le imputan una contumaz voluntad de incumplir las decisiones del tribunal de garantías, al reiterar la tramitación de las resoluciones a favor del derecho de autodeterminación y en contra del Rey Felipe VI.', 'https://cdnmundo4.img.sputniknews.com/images/107583/22/1075832241.jpg', '2020-02-02 14:42:52', 'El tribunal considera que la Mesa estaba "obligada', 'Policy', 'El país');
INSERT INTO noticias_reif.news (id, title, content, image, created_at, subtitle, section, author) VALUES (17, 'Qué debo comer según el tipo de deporte que practique', 'Si has empezado a ir al gimnasio, no vale con visitarlo un par de veces a la semana y, durante una hora, hacer unas cuantas repeticiones en las máquinas de entrenamiento. Aunque todo añadido siempre es bueno (hacer ejercicio, por poco que sea, nunca va a ser malo), si no estás atento a tu alimentación tus esfuerzos corren el peligro de caer en saco roto.
De este punto nace «Entrena tu alimentación», un libro de la coach nutricional Estefanía Fernández –conocida como @StefyActiva– en el que crea un decálogo de consejos para cuidar nuestra alimentación si entrenamos y hacemos deporte con regularidad, o incluso, si estamos empezando a adentrarnos en el mundo del entrenamiento.
Para empezar, es importante diferenciar qué objetivo perseguimos con el entrenamiento para adaptar nuestra dieta a ello. La coach nutricional apunta en primer lugar que es esencial, sea cual sea nuestra rutina de entrenamiento, que nuestra alimentación se base en un 80% en materias primas, es decir, alimentos naturales y frescos.', 'https://static4.abc.es/media/bienestar/2020/01/29/deporte-kgaD--620x349@abc.jpg', '2020-02-02 18:48:29', 'La coach nutricional Estefanía Fernández nos da co', 'Fitness', 'Estefanía Fernández');
INSERT INTO noticias_reif.news (id, title, content, image, created_at, subtitle, section, author) VALUES (18, 'Estas actividades deportivas serán tendencia en 2020', 'Aerial Hoop
El Aerial Hoop es un aparato de acero circular colgado en el techo, donde los artistas de circo pueden realizar acrobacias aéreas. Se puede usar estático, girando o balanceándose.
Pilates en barra
El pilates en barra es un ejercicio que combina las prácticas de ballet, pilates y yoga, por lo tanto, encontrarás ejercicios en la barra y en el suelo. La idea principal detrás de este ejercicio es encontrar el balance entre la mente y el cuerpo y se logra a través de ejercicios isométricos, con pequeñas repeticiones de movimientos específicos y el mantenimiento de esta posición por varios segundos para que el músculo se contraiga y se fortalezca.Pole Dance
El Pole Dance, también conocido como baile de tubo, ha estado fuertemente ligado con el table dance. Es una disciplina que implica que los bailarines realicen diversos movimientos en torno a un poste vertical. Sin embargo, en los últimos años ha adquirido fama y reconocimiento a nivel mundial. Es un ejercicio que requiere de gran fuerza y mucho control del cuerpo.', 'https://static4.abc.es/media/MM/2020/01/24/aerial-hoop-kPwB--1348x900@abc.jpg', '2020-02-02 22:52:34', 'Con la ayuda de Urban Sports Club descubrimos qué ', 'Fitness', 'ABC Bienestar');
INSERT INTO noticias_reif.news (id, title, content, image, created_at, subtitle, section, author) VALUES (19, 'Trekking', 'La definición que el diccionario de Cambridge de trekking es la actividad de hacer viajes largos y difíciles a pie. Aunque en castellano podemos utilizar palabras como senderismo o excursionismo, ninguno de ellos implica dificultad en sí mismos ni larga distancia. Por lo tanto, se puede considerar que el trekking es algo más que pasear. De hecho, el término se popularizó en el ámbito deportivo de la mano de los alpinistas que llamaban trekking a las caminatas para llegar al campamento base del Himalaya o de los Andes allá por los años 80.
El trekking es una actividad física en la que se recorren parajes naturales como bosques, montañas, cañones, selvas o ríos y que requieren más esfuerzo físico que el senderismo. Lo habitual es que su duración de varias jornadas por terrenos escapados y exigentes de ahí que los aficionados al trekking lo sean también a la acampada.
Imprescindible para quieres practican esta actividad es la planificación y diseñar las rutas de manera realista en lo que a la duración se refiere, teniendo en cuenta la capacidad física de los participante de modo que se pueda planificar cada etapa en función del relieve y de la dificultad para llegar a la zona de descanso o de acampada durante las horas de luz.', 'https://static3.abc.es/media/bienestar/2020/01/29/trekking-kqAH--620x349@abc.jpg', '2020-02-02 22:53:43', 'Trekking, la actividad de hacer viajes largos y di', 'Fitness', 'ABC Bienestar');
INSERT INTO noticias_reif.news (id, title, content, image, created_at, subtitle, section, author) VALUES (20, 'Los 5 canales de YouTube con los que podrás ponerte en forma', 'Si no tienes entrenador personal, también puedes entrenar por tu cuenta y conseguir los mismos resultados... Eso es posible gracias a algunas personalidades que hace años tomaron la decisión de abrirse un canal de YouTube para mostrar los ejercicios que realizan para estar en forma y, ya de paso, motivar a cientos de miles de personas a adoptar una rutina fitness que llevar a cabo con frecuencia.
Es así como en esta plataforma, además de encontrar música, tutoriales de belleza o recetas de cocina, también se ve un amplio abanico donde escoger con qué experto esculpir nuestra figura. Zumba, entrenamiento HIIT, pilates y multitud de disciplinas que se pueden desarrollar con solo un clic.1. Sergio Peinado  2. Gym Virtual 3. Fitonica 4. Sascha Fitness 5. Blogilates', 'https://static4.abc.es/media/bienestar/2020/01/27/fitness-youtube-kFCC--620x349@abc.jpg', '2020-02-02 22:55:10', 'La plataforma de vídeos tiene un amplio abanico de', 'Fitness', 'ABC Bienestar');
INSERT INTO noticias_reif.news (id, title, content, image, created_at, subtitle, section, author) VALUES (21, 'Esta es la playlist con la que se entrena Michelle Obama', 'La música nos acompaña a todos mientras hacemos ejercicio... y Michelle Obama no iba a ser menos. La ex primera dama de EE.UU ya ha mostrado en multitud de ocasiones ser una aficionada al deporte. La también activista, de 55 años, se mantiene en una forma envidiable y ella misma muestra, a través de Twitter e Instagram, algunas de sus rutinas de entrenamiento.
¿Lo último que ha compartido? La «playlist» que utiliza para entrenar. La lista de música, compuesta de 36 canciones, tiene temas tanto para los momentos más duros del entrenamiento como para la parte de estiramientos.
Como dice ella misma, «A veces es agradable el momento en el que estamos haciendo ejercicio, pero cuando terminamos, siempre nos alegramos de haber ido». Y no hay nada mejor que una buena «playlist» para acompañarnos en estos momentos.', 'https://static4.abc.es/media/bienestar/2020/01/21/michele-k3rF--620x349@abc.jpg', '2020-02-02 22:56:51', 'La ex primera dama estadounidense ha compartido la', 'Fitness', 'ABC Bienestar');
INSERT INTO noticias_reif.news (id, title, content, image, created_at, subtitle, section, author) VALUES (22, '«Subir escaleras o cargar la compra puede ser mejor que ir a', 'El entrenador personal Rober Sánchez lo tiene claro: somos incultos en lo que se refiere al movimiento. Concebimos hacer deporte como ejercicios repetitivos y poco dinámicos. Medimos nuestra actividad contando repeticiones en el gimnasio, kilómetros recorridos y calorías quemadas, pero el resto del día estamos en reposo. Somos «sedentarios activos».
Rober Sánchez cree que el movimiento debe ser otra cosa, y así lo cuenta en «Camina, salta, baila: muévete más y vive mejor», el libro que acaba de publicar y en el que desgrana el concepto de «movimiento», animándonos a analizar la manera en la que nos movemos día a día y a cambiar nuestros hábitos, para adaptarlo a lo que realmente demanda nuestro cuerpo.', 'https://static4.abc.es/media/bienestar/2020/01/21/subir-escaleras-kR9D--620x349@abc.jpg', '2020-02-02 22:57:14', 'El entrenador personal Rober Sánchez da las claves', 'Fitness', '');

