CREATE DATABASE noticias_reif;
USE DATABASE noticias_reif;

CREATE TABLE views(
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(40) NOT NULL,
    content VARCHAR(10000) NOT NULL,
    image VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)